name: Dependabot Extra

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 1' # Early Monday morning

permissions:
  contents: write
  pull-requests: write

jobs:
  update-ruby-version:
    uses: scott113341/workflows/.github/workflows/update-ruby-version.yaml@main
    secrets: inherit
